# Generated by Django 3.0.5 on 2020-06-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, null=True)),
                ('access_code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('requested_amount', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_url', models.URLField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
